name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
  - title: '🔒 Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
  default: patch
template: |
  ## Changes

  $CHANGES
  
  ## Performance
  
  This release includes performance improvements and optimizations for:
  - Parallel tool execution efficiency
  - Rate limiting accuracy and responsiveness  
  - Memory usage optimization
  - Speculation hit rate improvements
  
  ## Installation
  
  ```bash
  pip install async-toolformer-orchestrator==$RESOLVED_VERSION
  
  # With all optimizations
  pip install async-toolformer-orchestrator[full]==$RESOLVED_VERSION
  
  # Development installation
  git clone https://github.com/yourusername/async-toolformer-orchestrator.git
  cd async-toolformer-orchestrator
  git checkout v$RESOLVED_VERSION
  pip install -e ".[dev]"
  ```
  
  ## Docker
  
  ```bash
  docker pull async-toolformer/orchestrator:$RESOLVED_VERSION
  docker pull async-toolformer/orchestrator:latest
  ```
  
  ## Breaking Changes
  
  $BREAKING_CHANGES
  
  ## Migration Guide
  
  See [CHANGELOG.md](CHANGELOG.md) for detailed migration instructions.
  
  ## Security
  
  This release includes security updates. See [Security Policy](SECURITY.md) for vulnerability reporting.
  
  ---
  
  **Full Changelog**: https://github.com/yourusername/async-toolformer-orchestrator/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION