apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-toolformer-orchestrator-deployment
  namespace: async-toolformer
  labels:
    app: async-toolformer-orchestrator
    version: 1.0.0
    tier: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: async-toolformer-orchestrator
  template:
    metadata:
      labels:
        app: async-toolformer-orchestrator
        version: 1.0.0
    spec:
      containers:
        -
          name: async-toolformer-orchestrator
          image: async-toolformer-orchestrator:1.0.0
          ports:
            -
              containerPort: 8000
              name: http
            -
              containerPort: 9000
              name: metrics
          env:
            -
              name: ENVIRONMENT
              value: production
            -
              name: LOG_LEVEL
              value: INFO
            -
              name: REDIS_ENABLED
              value: True
            -
              name: MAX_CONCURRENT
              value: 50
            -
              name: CACHE_STRATEGY
              value: adaptive
            -
              name: OPTIMIZATION_STRATEGY
              value: aggressive
            -
              name: ENABLE_SPECULATION
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: True
            runAsUser: 1000
            readOnlyRootFilesystem: True
            allowPrivilegeEscalation: False
      serviceAccountName: async-toolformer-orchestrator-service-account
      automountServiceAccountToken: False
      securityContext:
        fsGroup: 1000