apiVersion: v1
kind: Namespace
metadata:
  name: async-toolformer
  labels:
    name: async-toolformer
    app.kubernetes.io/name: async-toolformer-orchestrator
    app.kubernetes.io/version: "0.1.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: async-toolformer-quota
  namespace: async-toolformer
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    persistentvolumeclaims: "4"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: async-toolformer-limits
  namespace: async-toolformer
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 1Gi
    type: PersistentVolumeClaim